---
- name: 'node-server'
  description: 'Node main server'
  trigger: 'node:server'
  scope: 'source.js'

- name: 'node-model'
  description: 'Mongoose Model defination'
  trigger: 'node:model'
  scope: 'source.js'

