---
- name: node-server
  description: Node main server
  trigger: node:server
  scope: source.js

- name: node-model
  description: Mongoose Model defination
  trigger: node:model
  scope: source.js

- name: node-ctrl
  description: Expressjs controller
  trigger: node:ctrl
  scope: source.js

- name: node-route
  description: Expressjs route
  trigger: node:route
  scope: source.js

- name: node-mount
  description: Expressjs mount routes
  trigger: node:mount
  scope: source.js

- name: node-use
  description: Express app.use() function
  trigger: node:use
  scope: source.js
# Mongoose snippes

- name: mon-find
  description: Mongoose find query method
  trigger: mon:find
  scope: source.js

- name: mon-find-one
  description: Mongoose findOne query method
  trigger: mon:findOne
  scope: source.js

- name: mon-find-by-id
  description: Mongoose findById query method
  trigger: mon:findById
  scope: source.js

- name: mon-find-one-and-update
  description: Mongoose findOneAndUpdate query method
  trigger: mon:findOneAndUpdate
  scope: source.js

- name: mon-find-one-and-remove
  description: Mongoose findOneAndRemove query method
  trigger: mon:findOneAndRemove
  scope: source.js

# Angular snippets
- name: ng-comp
  description: Angular 1 component
  trigger: ng:comp
  scope: source.js

- name: ng-on-init
  description: Angular onInit lifecycle hook
  trigger: ng:init
  scope: source.js

- name: ng-on-changes
  description: Angular onChanges lifecycle hook
  trigger: ng:change
  scope: source.js

- name: ng-on-destroy
  description: Angular onDestroy lifecycle hook
  trigger: ng:destroy
  scope: source.js

- name: ng-on-post-link
  description: Angular postLink lifecycle hook
  trigger: ng:link
  scope: source.js

- name: ng-module
  description: Angular Module
  trigger: ng:module
  scope: source.js

